version: '2'
services:
  probiblio-app:
    image: probiblio
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://probiblio-postgresql:5432/proBiblio
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  probiblio-postgresql:
    extends:
      file: postgresql.yml
      service: probiblio-postgresql
