version: '2'
services:
  probiblio-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/proBiblio/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=proBiblio
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
